module.exports = {
    DATABASE_CONNECTION: `Database is connected on "${process.env.DATABASE}"`,
    DATABASE_CONNECTION_ERROR: `Error in db connection`,
    ALL_READYEXIST:'allready exist',
    DATA_NOT_FOUND: 'not found',
    DATA_NOT_FOUND_EMAIL: 'not found by provided email',
    DATA_NOT_FOUND_ID: 'not found by provided id',
    UPDATE_PASSWORD: 'Password updated successfully',
    UPDATE_DATA: 'data updated successfully',
    REGISTER_SUCCESSFULLY :'registred successfully',
    LOGIN_SUCCESSFULLY :'You are logged in ',
    INVALID_PASSWORD: 'Invalid password provided',
    SUCCESSFULLY: 'data get successfully',
    SUCCESSFULLY_ADDED: 'data successfully added',
    SUCCESSFULLY_DELETED: 'data successfully deleted',
    OTP_SEND: 'OTP send successfully',
    OTP_NOT_MATCH: 'OTP not match or expired !',
    OTP_EXPIRED: 'OTP has expired',
    SUCCESSFULLY_RESET_PAGE: 'You redirect successfully "Reset Password Page"',
    PASS_MATCH_ERROR: 'Provide another password',
}