module.exports = {
    DATABASE_CONNECTION: `Database is connected on "${process.env.DATABASE}"`,
    DATABASE_CONNECTION_ERROR: `Error in db connection`,
    ALL_READYEXIST:'All ready exist',
    DATA_NOT_FOUND: 'Data not found',
    DATA_NOT_FOUND_EMAIL: 'user not found with provided email',
    DATA_NOT_FOUND_ID: 'user not found with provided id',
    UPDATE_PASSWORD: 'Password updated successfully',
    UPDATE_DATA: 'Data updated successfully',
    REGISTER_SUCCESSFULLY :'You are registred successfully',
    LOGIN_SUCCESSFULLY :'You are logged in ',
    INVALID_PASSWORD: 'Invalid password provided',
    SUCCESSFULLY: 'Data get successfully',
    SUCCESSFULLY_ADDED: 'Data add successfully',
    SUCCESSFULLY_DELETED: 'Data deleted successfully',
    OTP_SEND: 'OTP send successfully',
    OTP_NOT_MATCH: 'OTP not match or expired !',
    OTP_EXPIRED: 'OTP has expired',
    SUCCESSFULLY_RESET_PAGE: 'You redirect successfully "Reset Password Page"',
    PASS_MATCH_ERROR: 'Provide another password',
}